### PR TITLE
Added option to allow calculations on series. 

### PR DESCRIPTION
**Pull request by mbkupfer**
BLS Public Data API Signatures (Version 2.0) add the ability to query optional parameters.  Calculations is one of them. This new update now allows people to create a dictionary parameter in the `bls.api.get_series()` function. This of course will only work if users provide a key, but luckily the BLS server still provides values and simply omits the calculations if no key is provided. This makes crashing the program much less likely. I've also added some error messages to help users who do not provide correct values. 

Here is how it can be used to get net monthly changes for series id: CES000000000:

```
import bls
calcs = {
    'period' : 1,
    'calc_type': 'net_changes'
}

bls.get_series('CES0000000001', calculations=calcs)
```

Let me know what you think, as well as any improvements you think I can make here.

### CODE REVIEW

**Comment by mbkupfer** [comment]
Hi @OliverSherouse, looks like the flakes error is a styleguide convention which should be an easy fix. As for the other two errors from what I see, it looks like the error was the log message:
```
 api.py                      51 WARNING  Calculations have been disabled for this request.

```

This is the default reply if no key is used. Could we bypass this?

**Comment by OliverSherouse** [comment]
Tell you what, let me play around with the settings on Travis; I think we can actually have a testing Key there, which will allow that to go through. This is a cool feature; thanks for the PR!

**Comment by mbkupfer** [comment]
Hi @OliverSherouse any update on this?

**Comment by mbkupfer** [comment]
Closed this to reopen a new fork that was rebased.

That said, I'm happy to abandon this PR all together since many of these types of calcs can easily be done in pandas.

**Pull request closed without merging**
