### PR TITLE
Pull multiple series over arbitrary periods

### PR DESCRIPTION
**Pull request by kraemerd17**
This update would allow the API to specify arbitrary period lengths for BLS queries and for multiple series. For example, the call
```Python
get_series(['CUUR0000SA0','SUUR0000SA0'], startyear=2000, endyear=2015)
```
will return a pandas DataFrame containing the columns "CUUR0000SA0" and "SUUR0000SA0" with a date index from 2000-01-01 to 2015-12-01.

### CODE REVIEW

**Comment by kraemerd17** [comment]
Travis failed because 3.3 had a timeout. What might be causing that?

**Comment by OliverSherouse** [comment]
Sorry for the long delay on this. I'll check out what's going on with Travis.

More generally on the PR, I actually have been avoided using the Falsiness of None, because some potential non-None values are also falsy (specifically the empty string). Can we revert those out?

**Comment by kraemerd17** [comment]
To clarify, you're talking about the difference between

```
if None:
    ...
```

versus

```
if None is not None:
    ...
```
when it comes to truthiness, yes?

**Comment by OliverSherouse** [comment]
Alright, nevermind, I'm dumb; if users actually specify an empty key that should just be an error.  I'm not going to pull this directly into master (master is for releases only; I should clarify this in the docs), but I'll pull it into a branch off of dev, make a few minor style changes, figure out what's up with travis, and then merge it in (and add you to the contributor list, of course!).

**Pull request merged**
